version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
  digitas.api.web:
    image: ${DOCKER_REGISTRY-}digitasapi
    build:
      context: .
      dockerfile: Digitas.Api.Web/Dockerfile
      depends_on:
        - mongodb
  volumes:
    mongo